export const els = {
  setupPanel: document.querySelector("#setupPanel"),
  backButton: document.querySelector("#backButton"),
  missionPanel: document.querySelector("#missionPanel"),
  countPanel: document.querySelector("#countPanel"),
  settingsMenu: document.querySelector("#settingsMenu"),
  settingsButton: document.querySelector("#settingsButton"),
  settingsPanel: document.querySelector("#settingsPanel"),
  lightingSetting: document.querySelector("#lightingSetting"),
  popupSetting: document.querySelector("#popupSetting"),
  soundSetting: document.querySelector("#soundSetting"),
  musicSetting: document.querySelector("#musicSetting"),
  numbersSetting: document.querySelector("#numbersSetting"),
  roomMemorySetting: document.querySelector("#roomMemorySetting"),
  featureMissionButton: document.querySelector("#featureMissionButton"),
  similarityMissionButton: document.querySelector("#similarityMissionButton"),
  orderingMissionButton: document.querySelector("#orderingMissionButton"),
  carrollMissionButton: document.querySelector("#carrollMissionButton"),
  compareMissionButton: document.querySelector("#compareMissionButton"),
  simpleCompareMissionButton: document.querySelector("#simpleCompareMissionButton"),
  describeMissionButton: document.querySelector("#describeMissionButton"),
  hierarchyMissionButton: document.querySelector("#hierarchyMissionButton"),
  permutationMissionButton: document.querySelector("#permutationMissionButton"),
  pairCombinationMissionButton: document.querySelector("#pairCombinationMissionButton"),
  selectionMissionButton: document.querySelector("#selectionMissionButton"),
  teamMissionButton: document.querySelector("#teamMissionButton"),
  creatorMissionButton: document.querySelector("#creatorMissionButton"),
  vennMissionButton: document.querySelector("#vennMissionButton"),
  nestedMissionButton: document.querySelector("#nestedMissionButton"),
  countingMissionButton: document.querySelector("#countingMissionButton"),
  implicitMissionButton: document.querySelector("#implicitMissionButton"),
  workPanel: document.querySelector("#workPanel"),
  screenTitle: document.querySelector("#screenTitle"),
  countGrid: document.querySelector("#countGrid"),
  progressText: document.querySelector("#progressText"),
  featurePrompt: document.querySelector("#featurePrompt"),
  withHeader: document.querySelector("#withHeader"),
  withoutHeader: document.querySelector("#withoutHeader"),
  trayLabel: document.querySelector("#trayLabel"),
  tray: document.querySelector("#tray"),
  withZone: document.querySelector("#withZone"),
  withoutZone: document.querySelector("#withoutZone"),
  sortTable: document.querySelector("#sortTable"),
  similarityPanel: document.querySelector("#similarityPanel"),
  similarityStage: document.querySelector("#similarityStage"),
  similarityReference: document.querySelector("#similarityReference"),
  similarityChoices: document.querySelector("#similarityChoices"),
  orderingPanel: document.querySelector("#orderingPanel"),
  orderingZone: document.querySelector("#orderingZone"),
  criteriaList: document.querySelector("#criteriaList"),
  statisticsMissionButton: document.querySelector("#statisticsMissionButton"),
  averageMissionButton: document.querySelector("#averageMissionButton"),
  statisticsPanel: document.querySelector("#statisticsPanel"),
  statisticsInstruction: document.querySelector("#statisticsInstruction"),
  statisticsQuestion: document.querySelector("#statisticsQuestion"),
  statisticsFrequency: document.querySelector("#statisticsFrequency"),
  statisticsRankingDirection: document.querySelector("#statisticsRankingDirection"),
  statisticsOrderZone: document.querySelector("#statisticsOrderZone"),
  statisticsCoinStage: document.querySelector("#statisticsCoinStage"),
  statisticsCoinBank: document.querySelector("#statisticsCoinBank"),
  statisticsCoinShares: document.querySelector("#statisticsCoinShares"),
  statisticsWeightedTable: document.querySelector("#statisticsWeightedTable"),
  statisticsAnswerRow: document.querySelector("#statisticsAnswerRow"),
  carrollPanel: document.querySelector("#carrollPanel"),
  carrollTable: document.querySelector("#carrollTable"),
  carrollTopWith: document.querySelector("#carrollTopWith"),
  carrollTopWithout: document.querySelector("#carrollTopWithout"),
  carrollSideWith: document.querySelector("#carrollSideWith"),
  carrollSideWithout: document.querySelector("#carrollSideWithout"),
  carrollWithWithZone: document.querySelector("#carrollWithWithZone"),
  carrollWithoutWithZone: document.querySelector("#carrollWithoutWithZone"),
  carrollWithWithoutZone: document.querySelector("#carrollWithWithoutZone"),
  carrollWithoutWithoutZone: document.querySelector("#carrollWithoutWithoutZone"),
  comparePanel: document.querySelector("#comparePanel"),
  compareFaces: document.querySelector("#compareFaces"),
  compareCriteriaBank: document.querySelector("#compareCriteriaBank"),
  compareEqualZone: document.querySelector("#compareEqualZone"),
  compareDifferentZone: document.querySelector("#compareDifferentZone"),
  compareDragView: document.querySelector("#compareDragView"),
  compareTable: document.querySelector("#compareTable"),
  simpleComparePanel: document.querySelector("#simpleComparePanel"),
  simpleCompareFaces: document.querySelector("#simpleCompareFaces"),
  simpleCompareTable: document.querySelector("#simpleCompareTable"),
  describePanel: document.querySelector("#describePanel"),
  describePrompt: document.querySelector("#describePrompt"),
  describeSmiley: document.querySelector("#describeSmiley"),
  describeChoices: document.querySelector("#describeChoices"),
  hierarchyPanel: document.querySelector("#hierarchyPanel"),
  hierarchyTree: document.querySelector("#hierarchyTree"),
  permutationPanel: document.querySelector("#permutationPanel"),
  permutationOrderZone: document.querySelector("#permutationOrderZone"),
  albumPages: document.querySelector("#albumPages"),
  cameraButton: document.querySelector("#cameraButton"),
  pairCombinationPanel: document.querySelector("#pairCombinationPanel"),
  pairSourceA: document.querySelector("#pairSourceA"),
  pairSourceB: document.querySelector("#pairSourceB"),
  pairCaptureZone: document.querySelector("#pairCaptureZone"),
  pairAlbumPages: document.querySelector("#pairAlbumPages"),
  pairCameraButton: document.querySelector("#pairCameraButton"),
  teamPanel: document.querySelector("#teamPanel"),
  teamTitle: document.querySelector("#teamTitle"),
  teamSourceZone: document.querySelector("#teamSourceZone"),
  teamCaptureZone: document.querySelector("#teamCaptureZone"),
  teamAlbumPages: document.querySelector("#teamAlbumPages"),
  teamCameraButton: document.querySelector("#teamCameraButton"),
  selectionPanel: document.querySelector("#selectionPanel"),
  selectionStage: document.querySelector("#selectionStage"),
  selectionCaption: document.querySelector("#selectionCaption"),
  selectionTargetZone: document.querySelector("#selectionTargetZone"),
  selectionOkSlot: document.querySelector("#selectionOkSlot"),
  actionRow: document.querySelector("#actionRow"),
  creatorPanel: document.querySelector("#creatorPanel"),
  creatorCriteriaBank: document.querySelector("#creatorCriteriaBank"),
  creatorSmileyTarget: document.querySelector("#creatorSmileyTarget"),
  creatorResetButton: document.querySelector("#creatorResetButton"),
  creatorConfirmButton: document.querySelector("#creatorConfirmButton"),
  createdSmileys: document.querySelector("#createdSmileys"),
  vennPanel: document.querySelector("#vennPanel"),
  vennStage: document.querySelector("#vennStage"),
  vennAHead: document.querySelector("#vennAHead"),
  vennBHead: document.querySelector("#vennBHead"),
  vennCHead: document.querySelector("#vennCHead"),
  vennAZone: document.querySelector("#vennAZone"),
  vennBZone: document.querySelector("#vennBZone"),
  vennCZone: document.querySelector("#vennCZone"),
  vennABZone: document.querySelector("#vennABZone"),
  vennACZone: document.querySelector("#vennACZone"),
  vennBCZone: document.querySelector("#vennBCZone"),
  vennABCZone: document.querySelector("#vennABCZone"),
  vennOutsideZone: document.querySelector("#vennOutsideZone"),
  vennIntersectionPopup: document.querySelector("#vennIntersectionPopup"),
  nestedPanel: document.querySelector("#nestedPanel"),
  nestedStage: document.querySelector("#nestedStage"),
  nestedOuterHead: document.querySelector("#nestedOuterHead"),
  nestedInnerHead: document.querySelector("#nestedInnerHead"),
  nestedOuterZone: document.querySelector("#nestedOuterZone"),
  nestedInnerZone: document.querySelector("#nestedInnerZone"),
  nestedOutsideZone: document.querySelector("#nestedOutsideZone"),
  countingPanel: document.querySelector("#countingPanel"),
  countingStage: document.querySelector("#countingStage"),
  countingAHead: document.querySelector("#countingAHead"),
  countingBHead: document.querySelector("#countingBHead"),
  countingAClue: document.querySelector("#countingAClue"),
  countingBClue: document.querySelector("#countingBClue"),
  countingABClue: document.querySelector("#countingABClue"),
  countingUnionClue: document.querySelector("#countingUnionClue"),
  countingQuestion: document.querySelector("#countingQuestion"),
  countingAnswers: document.querySelector("#countingAnswers"),
  countingLabButton: document.querySelector("#countingLabButton"),
  vennMotionLab: document.querySelector("#vennMotionLab"),
  vennMotionLabClose: document.querySelector("#vennMotionLabClose"),
  vennMotionLabStage: document.querySelector("#vennMotionLabStage"),
  vennMotionLabCircleA: document.querySelector("#vennMotionLabCircleA"),
  vennMotionLabCircleB: document.querySelector("#vennMotionLabCircleB"),
  vennMotionLabSmileys: document.querySelector("#vennMotionLabSmileys"),
  vennMotionCountA: document.querySelector("#vennMotionCountA"),
  vennMotionCountBoth: document.querySelector("#vennMotionCountBoth"),
  vennMotionCountB: document.querySelector("#vennMotionCountB"),
  vennMotionPlayButton: document.querySelector("#vennMotionPlayButton"),
  vennMotionDistance: document.querySelector("#vennMotionDistance"),
  vennMotionSize: document.querySelector("#vennMotionSize"),
  implicitPanel: document.querySelector("#implicitPanel"),
  implicitAHead: document.querySelector("#implicitAHead"),
  implicitBHead: document.querySelector("#implicitBHead"),
  implicitChoiceList: document.querySelector("#implicitChoiceList"),
  implicitStage: document.querySelector("#implicitStage"),
  implicitAZone: document.querySelector("#implicitAZone"),
  implicitBZone: document.querySelector("#implicitBZone"),
  implicitABZone: document.querySelector("#implicitABZone"),
  implicitOutsideZone: document.querySelector("#implicitOutsideZone"),
  submitSortButton: document.querySelector("#submitSortButton"),
  celebration: document.querySelector("#celebration"),
  newSetButton: document.querySelector("#newSetButton"),
  smileyTemplate: document.querySelector("#smileyTemplate")
};

export function getAllDropContainers() {
  return [
    els.tray,
    els.withZone,
    els.withoutZone,
    els.orderingZone,
    els.statisticsOrderZone,
    els.permutationOrderZone,
    els.pairSourceA,
    els.pairSourceB,
    els.pairCaptureZone,
    els.teamSourceZone,
    els.teamCaptureZone,
    els.carrollWithWithZone,
    els.carrollWithoutWithZone,
    els.carrollWithWithoutZone,
    els.carrollWithoutWithoutZone,
    els.vennAZone,
    els.vennBZone,
    els.vennCZone,
    els.vennABZone,
    els.vennACZone,
    els.vennBCZone,
    els.vennABCZone,
    els.vennOutsideZone,
    els.nestedOuterZone,
    els.nestedInnerZone,
    els.nestedOutsideZone,
    els.countingAClue,
    els.countingBClue,
    els.countingABClue,
    els.implicitAZone,
    els.implicitBZone,
    els.implicitABZone,
    els.implicitOutsideZone,
    els.selectionTargetZone,
    ...Array.from(document.querySelectorAll("[data-zone^='hierarchy-node-']")),
    ...Array.from(document.querySelectorAll("[data-zone^='statistics-beard-']"))
  ].filter(Boolean);
}

export function getZoneElement(zone) {
  if (zone.startsWith("hierarchy-node-")) return document.querySelector(`[data-zone="${CSS.escape(zone)}"]`);
  if (zone === "order") return els.orderingZone;
  if (zone === "statistics-order") return els.statisticsOrderZone;
  if (zone === "pair-source-a") return els.pairSourceA;
  if (zone === "pair-source-b") return els.pairSourceB;
  if (zone === "pair-capture") return els.pairCaptureZone;
  if (zone === "team-source") return els.teamSourceZone;
  if (zone === "team-capture") return els.teamCaptureZone;
  if (zone.startsWith("statistics-beard-")) return document.querySelector(`[data-zone="${CSS.escape(zone)}"]`);
  if (zone === "permutation-order") return els.permutationOrderZone;
  if (zone === "with") return els.withZone;
  if (zone === "without") return els.withoutZone;
  if (zone === "carroll-with-with") return els.carrollWithWithZone;
  if (zone === "carroll-without-with") return els.carrollWithoutWithZone;
  if (zone === "carroll-with-without") return els.carrollWithWithoutZone;
  if (zone === "carroll-without-without") return els.carrollWithoutWithoutZone;
  if (zone === "venn-a") return els.vennAZone;
  if (zone === "venn-b") return els.vennBZone;
  if (zone === "venn-c") return els.vennCZone;
  if (zone === "venn-ab") return els.vennABZone;
  if (zone === "venn-ac") return els.vennACZone;
  if (zone === "venn-bc") return els.vennBCZone;
  if (zone === "venn-abc") return els.vennABCZone;
  if (zone === "venn-outside") return els.vennOutsideZone;
  if (zone === "nested-outer") return els.nestedOuterZone;
  if (zone === "nested-inner") return els.nestedInnerZone;
  if (zone === "nested-outside") return els.nestedOutsideZone;
  if (zone === "counting-a") return els.countingAClue;
  if (zone === "counting-b") return els.countingBClue;
  if (zone === "counting-ab") return els.countingABClue;
  if (zone === "selection-target") return els.selectionTargetZone;
  if (zone === "implicit-a") return els.implicitAZone;
  if (zone === "implicit-b") return els.implicitBZone;
  if (zone === "implicit-ab") return els.implicitABZone;
  if (zone === "implicit-outside") return els.implicitOutsideZone;
  return els.tray;
}
